---
#- hosts: microk8s
#  become_user: "{{ k8s_user.name }}"
#  tasks:
#    - include_role:
#        name: microk8s

- hosts: microk8s
  become_user: "{{ k8s_user.name }}"
  tasks:
    - name: "installs/configures longhorn"
      include_role: 
        name: longhorn
