- name: ensure fluxcd namespace exists in cluster
  k8s:
    name: "{{ flux_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "add helm repo for flux"
  community.kubernetes.helm_repository:
    name: fluxcd
    repo_url: https://charts.fluxcd.io

- name: "get helm charts"
  get_url:
    url: "https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/crds.yaml"
    dest: "/tmp/flux-helm-cards.yaml"

- name: "apply helm flux config"
  community.kubernetes.k8s:
    state: present
    src: /tmp/flux-helm-cards.yaml
    apply: yes
  changed_when: false

- debug: var=git_branch

- name: "ensure kustomize config dir exists"
  file:
    path: "{{ kustomize_dir }}"
    state: directory
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"

- name: "export templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
  with_items:
    - src: "flux.kustomization.yaml.j2"
      dest: "{{ kustomize_dir }}/kustomization.yaml"
    - src: "flux.namespace.yaml.j2"
      dest: "{{ kustomize_dir }}/namespace.yaml"
    - src: "flux.patch.yaml.j2"
      dest: "{{ kustomize_dir }}/patch.yaml"
  register: stat

- name: "configures flux"
  command: "microk8s kubectl apply -k {{ kustomize_dir }}"
#  when: stat.changed