- assert:
    that: "{{ item }} is defined"
    msg: "{{ item }} variables should be defined"
  with_items:
    - github_user
    - github_repo
    - git_branch
    - k8s_user
    - k8s_plugins
    - k8s_static
    - flux_namespace

- name: update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 600

- name: ensure required packages installed
  become: true
  package:
    name:
      - snapd
      - python3-pip
    state: present

- name: "include microk8s install tasks"
  include_tasks: microk8s.yml

- name: "include microk8s user config"
  include_tasks: user.yml

- name: ensure python libraries installed
  pip:
    name:
      - kubernetes
      - openshift
    state: present

- import_tasks: netplan.yml
#- import_tasks: flux.yml
