- assert:
    that: "{{ item }} is defined"
    msg: "{{ item }} variables should be defined"
  with_items:
    - github_user
    - github_repo
    - git_branch
    - k8s_user.name
    - k8s_user.group
    - k8s_plugins
    - k8s_static
    - flux_namespace
    - k8s_netplan_gateway
    - k8s_netplan_dns
    - k8s_netplan_interface

- name: update apt cache
  apt:
    update_cache: true
    cache_valid_time: 600

- name: "configures networking"
  import_tasks: netplan.yml
  when: configure_netplan

#- name: "include microk8s install tasks"
#  include_tasks: microk8s.yml

- name: "load kernel modules"
  community.general.modprobe:
    name: "br_netfilter"
    state: present

- name: "install docker"
  include_role:
    name: "geerlingguy.docker"

- name: "install microk8s"
  include_tasks: microk8s.yml

- name: ensure python libraries installed
  pip:
    name:
      - kubernetes
      - openshift
    state: present


#- name: "configures helm"
#  include_tasks: helm.yml
  