- name: ensure k8s user exists
  user:
    name: "{{ k8s_user }}"
    state: present

- name: ensure microk8s required package installed
  snap:
    name:
      - microk8s
      - kubectl
      - fluxctl
      - helm
    classic: yes
    state: present

- name: microk8s status
  command: "{{ microk8s_cmd }} status --wait-ready"
  register: status
  changed_when: false

- name: ensure microk8s modules enabled
  command: "microk8s.enable {{ item }}"
  with_items: "{{ k8s_plugins }}"
  changed_when: false

- name: set alias
  lineinfile:
    path: "/home/{{ k8s_user }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "alias helm='microk8s helm'"
    - "alias kubectl='microk8s kubectl'"