- name: ensure required packages installed
  package:
    name:
      - snapd
      - python3-pip
    state: present

- name: ensure snapd service enabled and started
  service:
    name: snapd
    enabled: true
    state: started

- name: ensure microk8s required package installed
  snap:
    name:
      - microk8s
      - kubectl
      - helm
    classic: yes
    state: present

- name: wait microk8s status ready
  command: "{{ microk8s_cmd }} status --wait-ready"
  register: status
  changed_when: false

- name: "include microk8s user config"
  include_tasks: user.yml

- name: "reset ssh connections"
  meta: flush_handlers

- name: ensure microk8s modules enabled
  become_user: "{{ k8s_user.name }}"
  command: "/snap/bin/microk8s.enable {{ item }}"
  with_items: "{{ k8s_plugins }}"
  changed_when: false