- name: add user to microk8s group
  become: true
  user:
    name: "{{ k8s_user }}"
    groups: microk8s
    append: yes

- name: configures user
  file:
    path: "/home/{{ k8s_user }}/.kube"
    state: directory
    owner: "{{ k8s_user }}"

- stat: 
    path: "{{ kube_config_path }}"
  register: _kube_config_stat

- name: dump microk8s config
  become: true
  shell: 
    cmd: "microk8s config >> {{ kube_config_path }}"
    creates: "{{ kube_config_path }}"
  #when: "{{ true != _kube_config_stat.stat.exists }}"

- name: change config file mode
  become: true
  file:
    path: "{{ kube_config_path }}"
    mode: "0600"
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"
