---
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options: []
    #login_cmd_template: 'ssh localhost -p 2222 -i .vagrant/machines/default/virtualbox/private_key'

    #  ansible_user: vagrant
    #  ansible_host: localhost
    #  ansible_port: 2222

platforms:
  - name: hercules


provisioner:
  name: ansible
  log: true
  inventory:
    links:
      hosts: inventory/hosts.ini
      group_vars: inventory/group_vars
      host_vars: inventory/host_vars
  playbooks:
    converge: ../../playbook.yml

verifier:
  name: ansible