k8s_plugins:
  - dns
  - dashboard
  - storage
  - ingress
  - helm3

k8s_netplan_interface: enp0s3
k8s_netplan_dns: [ 1.1.1.1 ]
k8s_netplan_gateway: 10.18.0.1
k8s_static:
  ip_start: 2
  ip_end: 254
  ip_prefix: 192.168.20

configure_netplan: yes
configure_rancher: yes